sonar.organization=sepaseh
sonar.sources=src
sonar.tests=src,e2e
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.stories.tsx,e2e/**/*.spec.ts
sonar.exclusions=src/**/*.d.ts,src/**/*.test.ts,src/**/*.test.tsx,src/**/*.stories.tsx,src/assets/fonts/**,src/test/**
sonar.coverage.exclusions=src/**/*.d.ts,src/**/*.test.ts,src/**/*.test.tsx,src/**/*.stories.tsx,src/**/index.ts,src/main.tsx,src/test/**,src/features/**/types.ts,src/shared/api/types.ts
sonar.cpd.exclusions=src/**/*.stories.tsx,src/test/storybook/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=false
sonar.issue.ignore.multicriteria=asyncHandlers
sonar.issue.ignore.multicriteria.asyncHandlers.ruleKey=typescript:S6544
sonar.issue.ignore.multicriteria.asyncHandlers.resourceKey=**/*.tsx
