sonar.sources=src
sonar.tests=src,e2e
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,e2e/**/*.spec.ts
sonar.exclusions=src/**/*.d.ts,src/**/*.test.ts,src/**/*.test.tsx,src/test/**
sonar.coverage.exclusions=src/**/*.d.ts,src/**/*.test.ts,src/**/*.test.tsx,src/**/index.ts,src/main.tsx,src/test/**,src/types/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.qualitygate.wait=true
